export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const DESELECT_CATEGORY = "DESELECT_CATEGORY";

export const SELECT_FOOD = "SELECT_FOOD";
export const DESELECT_FOOD = "DESELECT_FOOD";

export const APPLY_FILTER = "APPLY_FILTER";
